name: CI

on:
  push:
    branches: v8.3
  pull_request:

jobs:
  pipeline:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker build --tag ghcr.io/gaming-platform/docker-php-fpm:8.3-development \
                       .
          docker build --build-arg environment=production \
                       --build-arg php_opcache_jit_buffer_size=256M \
                       --build-arg php_opcache_validate_timestamps=0 \
                       --build-arg php_zend_assertions=-1 \
                       --build-arg php_http_log_flush=5s \
                       --tag ghcr.io/gaming-platform/docker-php-fpm:8.3-production \
                       .

      - name: Deploy
        if: github.ref == 'refs/heads/v8.3'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/gaming-platform/docker-php-fpm:8.3-development
          docker push ghcr.io/gaming-platform/docker-php-fpm:8.3-production
