name: CI

on:
  push:
    branches: v7.4
  pull_request:

jobs:
  pipeline:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker build --file development/Dockerfile \
                       --tag ghcr.io/gaming-platform/docker-php-fpm:7.4-development \
                       .
          docker build --file production/Dockerfile \
                       --tag ghcr.io/gaming-platform/docker-php-fpm:7.4-production \
                       .

      - name: Deploy
        if: github.ref == 'refs/heads/v7.4'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/gaming-platform/docker-php-fpm:7.4-development
          docker push ghcr.io/gaming-platform/docker-php-fpm:7.4-production
