name: CI

on:
  push:
    branches: v8.0
  pull_request:

jobs:
  pipeline:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker build --tag gamingplatform/php-fpm:8.0-development \
                       .
          docker build --build-arg environment=production \
                       --build-arg php_opcache_jit_buffer_size=256M \
                       --build-arg php_opcache_validate_timestamps=0 \
                       --build-arg php_zend_assertions=-1 \
                       --tag gamingplatform/php-fpm:8.0-production \
                       .

      - name: Deploy
        if: github.ref == 'refs/heads/v8.0'
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push gamingplatform/php-fpm:8.0-development
          docker push gamingplatform/php-fpm:8.0-production
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
